version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Set MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: 1234 # Set MongoDB root password
    volumes:
      - mongodb-data:/data/db # Persist MongoDB data

volumes:
  mongodb-data:
    driver: local

